### ISSUE TITLE
Run multiple templates in one run?

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#10]
This was more a query and possibly feature request. [Panzer](https://github.com/msprev/panzer) offers the ability to run multiple `styles` (what pandocomatic calls templates) from one pandoc source file. Did I miss this feature in the documentation, or if not, would it be something worth adding?

```yaml
pandocomatic_:
  use-template: my_word
    pandoc:
      to: docx
  use-template: my_pdf
    pandoc:
      to: pdf
```
