### ISSUE TITLE
--config option does not replace the default pandocomatic.yaml?

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#119]
I was trying to help someone debug a pandocomatic problem (which I thought was a faulty default pandocomatic.yaml file), by testing a different options yaml using `--config`, but I noticed that although pandocomatic logs it uses the `--config` yaml, the settings actually are coming from the default `~/.local/share/pandoc/pandocomatic.yaml`:

A sample options yaml, save as pmatic.yaml:

```yaml
templates:
  refs:
    pandoc:
      reference-links: true
    metadata:
      notes-after-punctuation: false
  latex:
    pandoc:
      from: markdown
      to: latex-smart
      standalone: true
      template: templates/custom.latex
    metadata:
      documentclass: 'article'
  latex-refs:
    extends: [latex, refs]
  docx:
    pandoc:
      from: markdown
      to: docx
      standalone: true
      reference-doc: templates/custom.docx
  docx-refs:
    extends: [docx, refs]
```

In the directory where pmatic.yaml is saved, create a minimal test md:

```shell
echo "---\ntitle: Hi\npandocomatic:\n  use-template: latex-refs\n---\n\nTest" > test.md
```

Now try to use `pmatic.yaml` to compile `test.md`, logging our status:

```shell
pandocomatic --config ./pmatic.yaml --log-level debug --log pmatic.log test.md
```

The `pmatic.log` shows:

```
2025-03-28 09:12:41 INFO : ------------ START ---------------
2025-03-28 09:12:41 INFO : Running /Users/ian/.pixi/bin/pandocomatic --config pmatic.yaml --log-level debug --log pmatic.log test.md
2025-03-28 09:12:41 DEBUG: Validating command-line arguments:
2025-03-28 09:12:41 DEBUG: ✓  Option '--input' not used:  treat all arguments after last option as input files or directories.
2025-03-28 09:12:41 DEBUG: ✓  Convert single input file or directory.
2025-03-28 09:12:41 DEBUG: ✓  Input files and directories exist.
2025-03-28 09:12:41 DEBUG: ✓  Can read configuration file 'pmatic.yaml'.
2025-03-28 09:12:41 DEBUG: Start conversion:
2025-03-28 09:12:41 INFO : (2) + converting /Users/ian/Desktop/test.md 1 time:
2025-03-28 09:12:41 INFO : (1)   - convert test.md -> test.tex
2025-03-28 09:12:41 DEBUG:   #  Using template 'latex-refs'.
...
2025-03-28 09:12:41 DEBUG:      | MetadataPreprocessor. Adding mined YAML blocks to metadata:
                                     notes-after-punctuation: false
                                     link-citations: true
                                     link-bibliography: true
                                     csl-hanging-indent: true
...
```

The metadata is not coming from `pmatic.yaml` but from my default. If the markdown specifies a template that doesn't exist in `pmatic.yaml` compilation still works (there is no typst template in pmatic.yaml):

```
2025-03-28 09:15:38 DEBUG: ✓  Can read configuration file 'pmatic.yaml'.
2025-03-28 09:15:38 DEBUG: Start conversion:
2025-03-28 09:15:38 INFO : (2) + converting /Users/ian/Desktop/test.md 1 time:
2025-03-28 09:15:38 INFO : (1)   - convert test.md -> test.typst
2025-03-28 09:15:38 DEBUG:   #  Using template 'typst'.
```

Even specifying a different data dir does not stop the default being mixed in:

```
pandocomatic -d '/Users/ian/Desktop' --config pmatic.yaml --log-level debug --log pmatic.log test.md
```

It wasn't clear what the expected behaviour should be from the docs:

https://heerdebeer.org/Software/markdown/pandocomatic/#arguments-to-configure-pandocomatic

Is the merging a design feature? It does complicate switching to use a different template fully. Thanks Huub!

**Comment by htdebeer** [comment]
I am not sure this is expected behavior or not. Behavior was introduced for #15, eight years ago, so users might have come to depend on this behavior.

Looking in the code, templates are merged with templates of the same name from earlier loaded configurations. Maybe templates of the same name should be replaced instead? I cannot oversee what for effect this'll have, though, for existing configuration files / templates people might use.

I can experiment with replacing rather than merging, and investigate further, but that'll take some time.

For now, as a workaround, would using new names for templates that should replace earlier defined ones prevent this problem from happening?

**Comment by iandol** [comment]
In #15 I think the original idea was to inherit templates within a single config file (and `extends` is awesome) and also merge with document cofig YAML. Merging the same named template across files is a slightly different thing. 

I suppose I can understand a usecase: a default pandocomatic.yaml defines the base, we can add template data to the document to modify the base. We add a new `-c` yaml to also merge further? 

But this also seems redundant (why use another config file when the base + document already provides general + specific layering). The command-line help:

> Configure pandocomatic to use PATH as its configuration file to use during the conversion process

It reads to me like `-c` replaces any other config files. I think quietly inheriting config is more than not confusing.

> For now, as a workaround, would using new names for templates that should replace earlier defined ones prevent this problem from happening?

Do you mean: if I have `DATA_DIR/pandocomatic.yaml` and I specify `-c ./pandocomatic.yaml` it merges and if I specify `-c ./newconfig.yaml` it replaces? It would certainly work for me, but this may still possibly affect some existing users?

Another possibility is leave `-c` behaviour as-is and add a new command-line option, `-n --new-config` that would always replace `DATA_DIR/pandocomatic.yaml`, this way existing users are not impacted just-in-case and we can now use clean configs?

**Comment by htdebeer** [comment]
For the workaround I meant that you could rename your templates so they don't match one of the parent configuration files.

But I agree that at first sight this seems like a bug. Will investigate if we want to fix it, or add an option to switch between the current behavior and the new behavior.

**Comment by iandol** [comment]
> For the workaround I meant that you could rename your templates so they don't match one of the parent configuration files.

In my original example the two YAML files have different names already?

**Comment by htdebeer** [comment]
For the workaround, I was not talking about the names of the YAML files, but about the names of the templates in the YAML files. For example, when I reproduce your scenario with the following default template:

```yaml
# ~/.local/share/pandoc/pandocomatic.yaml
settings:
  recursive: true
templates:
  latex:
    metadata:
      author: Huub de Beer
```

The metadata author gets mixed in when executing your example

```bash
pandocomatic --config ./pmatic.yaml --log-level debug --log pmatic.log test.md
```

If I rename template "latex" in `pmatic.yaml` to "latex-custom", the metadata doesn't get author mixed in. Thus:

```yaml
# ./pmatic.yaml
templates:
  refs:
    pandoc:
      reference-links: true
    metadata:
      notes-after-punctuation: false
  latex2:
    pandoc:
      from: markdown
      to: latex-smart
      standalone: true
      template: templates/custom.latex
    metadata:
      documentclass: 'article'
  latex-refs:
    extends: [latex2, refs]
  docx:
    pandoc:
      from: markdown
      to: docx
      standalone: true
      reference-doc: templates/custom.docx
  docx-refs:
    extends: [docx, refs]
```

**Comment by htdebeer** [comment]
It seems that the issue is that when extending a template, all templates in the configuration chain with the same name name are mixed in. Whereas the expectation is that only the most closest template gets mixed in.

In this case, template "latex-refs" extends "latex" and "refs". This "latex" template is already defined in the same file, but also in the default configuration. It should only mix in the one in the same file, not also the one in the default configuration.

The latter behavior I'd only expect when the template in the file also extends "latex", i.e.:

```yaml
# ./pmatic.yaml
templates:
  refs:
    pandoc:
      reference-links: true
    metadata:
      notes-after-punctuation: false
  latex:
    extends: latex
    pandoc:
      from: markdown
      to: latex-smart
      standalone: true
      template: templates/custom.latex
    metadata:
      documentclass: 'article'
  latex-refs:
    extends: [latex, refs]
  docx:
    pandoc:
      from: markdown
      to: docx
      standalone: true
      reference-doc: templates/custom.docx
  docx-refs:
    extends: [docx, refs]
```
