### ISSUE TITLE
[Feature request] Inheritable Templates

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#15]
Hi, in [Panzer](https://github.com/msprev/panzer), you can define a style, and then you can inherit that style in another styles like so:

```yaml
base:
  all:
    metadata:
      bibliography: "core.bib"  
      csl: "apa.csl"
    commandline:
      smart: true
article:
  parent: base
  all:
      commandline:
        table-of-contents: true
      filter: 
        - run: pandoc-citeproc
```

This is quite a nice way to manage templates, reusing a base set of settings then changing just what is needed. Nothing major, just worth thinking about for a future version.

**Comment by htdebeer** [comment]
That would be great, yes. 

Do note that it is [already sort of possible](https://heerdebeer.org/Software/markdown/pandocomatic/#using-pandocomatic-templates), although I am not sure to the extent it works. You can override templates in a parent context, but that is less explicit than Panzer is doing.

Maybe we should rethink the way templates are handled for version 0.2 and start gathering ideas of what we want. I'll create a new milestone to gather these type of request.

**Comment by htdebeer** [comment]
I added an "extends" option for template. It can take a single String or an Array of Strings. For example:

```
templates:
    now:
        preprocessors: ['preprocessors/now.rb']
    check-links:
        postprocessors: ['postprocessors/checklinks.sh']
    my-page:
        extends: 'now'
        pandoc:
             from: markdown
             to: html
     another-page:
         extends: ['my-page', 'check-links']
         pandoc:
              template: 'templates/another_template.html'
```

A template is build starting from the extended templates and then mixin in the template-specific properties. In the above example, the 'another-page' template is constructed as follows:

- {}
- {} ← wiki-page
- {} ← wiki-page ← check-links
- {} ← wiki-page ← check-links ← pandoc: template: ....

Starting with an empty Hash, each template to extend is merged with the Hash from the previous merge or the empty merge at step two. Finally, the properties from the actual template are merged as well. In the end, the 'another-page' template would have all the properties from the previous templates.
