### ISSUE TITLE
[Feature request] Metadata Management

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#16]
Again inspired by [Panzer](https://github.com/msprev/panzer), it would be nice to be able to set up Metadata for templates as well as pandoc options. 

```yaml
Notes:
    latex:
        metadata:
            numbersections: true
            fontsize: 12pt
        commandline:
            wrap: preserve
        filter:
            - run: deemph.py
```

Metadata is important for fully setting Pandoc's conversion, though again we can use our Document metadata for this it would make Pandocomatic more flexible. I think we can use the pandoc `metadata` and `variable` options (haven't tested yet), but it seems less clean. Something to think about for a future version?

**Comment by iandol** [comment]
I tried to set metadata in the template and failed:

```yaml
  paper-with-refs-pdf:
    preprocessors: []
    pandoc:
      from: markdown
      to: latex
      standalone: true
      filter: pandoc-citeproc
      bibliography: core.bib
      csl: apa.csl
      metadata:
        - documentclass: "article"
        - lang: "en-GB"
        - papersize: "A3"
        - fontsize: "16pt" 
        - linestretch: "1.75"
      toc: true
      toc-depth: 4
      base-header-level: 1
    postprocessors: []
```
