### ISSUE TITLE
Footnote becomes corrupted in Pandocomatic

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#22]
The following markdown gets mangled in pandocomatic, but works fine in Pandoc. The Test footnote B... becomes corrupted like so: 

```html
<h2 id="cf2-4-march-2007-at-1549-test-footnote-b">[^cf2]: 4 March 2007 at 15:49 Test footnote B…</h2>
<p>fileinfo: path: 'Blank3.md' created: 2017-05-12 modified: 2017-05-12 ...</p>
```

This fileinfo is injected by https://github.com/htdebeer/pandocomatic/blob/master/lib/pandocomatic/fileinfo_preprocessor.rb#L29 and I think the problem is the footnote has no newline after it and the metadata block needs a blank line before it for it to be correctly parsed by pandoc...

```markdown
---
title: "Test Project"
author: John Doe
pandocomatic_:
  use-template: test
---

# Abstract #

Pro in accusamus delicatissimi, ad vis tota tacimates, ius wisi ponderum ea. Et vis novum quaeque persecuti, mei cu magna delicata, mei omnes ceteros molestie id[^cf1], pri an denique honestatis consequuntur[^cf2].  

[^cf1]: 4 March 2007 at 15:49 Test footnote A…

[^cf2]: 4 March 2007 at 15:49 Test footnote B…
```

```yaml
  test:
    preprocessors: []
    pandoc:
      from: markdown
      to: html5
      standalone: true
      self-contained: true
      mathjax: true
      dpi: 300
      toc: false
    postprocessors: []
```
