### ISSUE TITLE
Filters and pandoc-citeproc in docx template

### ISSUE THREAD

**Issue by talazem** [htdebeer/pandocomatic#36]
I have a Pandocomatic issue whilst using the `authorRemoveHash` filter when outputting to docx, using citeproc. 

I may be misunderstanding this, but — in the `docx-with-refs` template — I must repeat my invoking of the pandoc-crossref, pandoc-citeproc, and pandoc-citeproc-preamble filters, even though they were invoked in the `refs` template above. Without doing this, if I invoked the `removeHR` and `authorRemoveHash` filters, citeproc was not working.

The following are the relevant parts of the pandocomatic.yaml file. In `docx-with-refs` I have escaped the three filters already invoked by `refs`. This results in the error described. Unescape them, and everything works as expected.

settings:
recursive: true
follow-symlinks: false
skip: ['.*', 'pandocomatic.yaml']
templates:
#######################################
refs:
pandoc:
standalone: true
filter: 
\- pandoc-crossref
\- pandoc-citeproc #process citations
\- pandoc-citeproc-preamble
bibliography: /Users/name/.pandoc/Bibliography.bib
csl: /Users/name/.pandoc/csl/chicago-note-bibliography.csl
number-sections: true # required by pandoc-crossref for LaTeX/PDF output, recommended for other output formats
metadata:
notes-after-punctuation: true
link-citations: true 
#######################################
docx:
setup: []
preprocessors: []
pandoc:
from: markdown
to: docx
standalone: true
dpi: 300
reference-docx: '/Users/name/.pandoc/templates/reference.docx'
number-sections: true # required by pandoc-crossref for LaTeX/PDF output, recommended for others
postprocessors: []
cleanup: []
#######################################
docx-with-refs:
extends: ['refs','docx']
pandoc:
filter: 
\# - pandoc-crossref
\# - pandoc-citeproc #process citations
\# - pandoc-citeproc-preamble
\- '/Users/name/.pandoc/filters/removeHR' #remove horizontal rules
\- '/Users/name/.pandoc/filters/authorRemoveHash' #converts author metadata for Word
#######################################

There may be other dependencies I am overlooking, but perhaps this is a starting point.

**Comment by iandol** [comment]
Just to clarify, these filters (`authorRemoveHash` and `removeHR`) are not part of pandocomatic, but user filters. The issue seems to be, with TEMPLATEA being the parent of TEMPLATEC that the inheritance of the filters from A fails if C specifies extra filters? I will try and test this (though I can't do this before a few days) and see if I can reproduce.

**Comment by htdebeer** [comment]
I'll have a look at this in the weekend.

It might have something to do with merging "list parameters" (or the lack thereof). Is the same thing happening for, say, the `--css` parameters: if you'd set CSS files in the parent and in the child, does the CSS files of the parent show up when using the child template?

Fundamentally, how should list parameters be merged when extending a template? Should they? Should you be able to remove or overwrite list elements from the parent?

**Comment by iandol** [comment]
I made a simple test case and can confirm this behaviour:

```yaml
#######################################     
  test-A:    
    pandoc:
      from: markdown
      to: html5
      standalone: true
      css: '/Users/ian/.pandoc/templates/custom.css'
      filter: '/Users/ian/.pandoc/filters/noop'
 #######################################     
  test-B:    
    pandoc:
      filter: '/Users/ian/.pandoc/filters/noopB'
 #######################################     
  test-C:   
    extends: ['test-A','test-B'] 
    pandoc:
      css: '/Users/ian/.pandoc/templates/customC.css'
      filter: '/Users/ian/.pandoc/filters/noopC'
```

```markdown
---
title: "Test"
pandocomatic:
  use-template: test-C
---

# Abstract #

Blah blah blah.
```

```
👉  pandocomatic -b -i 'Lu.md'
pandoc	--from=markdown \
	--to=html5 \
	--standalone \
	--css=/Users/ian/.pandoc/templates/customC.css \
	--filter=/Users/ian/.pandoc/filters/noopC
Pandocomatic needed 0.8 seconds to convert 'Lu.md'.
```
So yes, the parent filters and CSS are lost and overwritten by the child items. I had naively assumed for list parameters they were merged, but in my templates never needed to use merging so never saw this when I inherited from parents (my parent only ever contains pandoc-citeproc, which is called even if you don't call it when you have --Bibliography defined). I think merging is generally more flexible than replacing, but the problem is if you do want to override the parent, how can you do that? In that case the benefit of replacement is you can handle merge (manually) and replace. This is less elegant but more practical. 

```yaml
#######################################     
  test-C:   
    extends: ['test-A','test-B'] 
    pandoc:
      css: 
        - 'replaceListItems!'
        - '/Users/ian/.pandoc/templates/customC.css' # this replaces
      filter: '/Users/ian/.pandoc/filters/noopC' # this merges
```

One possible solution is to append a custom tag, and pandocomatic would parse the yaml to determine items to merge/replace, but though the best of both worlds it is inelegant IMO.
