### ISSUE TITLE
Resolving Filter Paths

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#37]
With a filter `removeHR` in `DATA-DIR/filters` with Pandoc we can do this:

```
pandoc -F removeHR -o Lu.docx 'Lu.md'
```

And pandoc will search `DATA-DIR/filters` to use the filter. However if I use no path in pandocomatic.yaml, pandocomatic rewrites the root data-dir and pandoc fails:

```yaml
#######################################
  docx-with-refs:
    pandoc:
      filter: 
        - 'removeHR' #remove horizontal rules
```

```
Error running pandoc => error while running:

pandoc	--standalone \
	--filter=/Users/ian/.pandoc/removeHR \
	--bibliography=/Users/ian/.pandoc/Core.json \
	--csl=/Users/ian/.pandoc/csl/neuron.csl \
	--from=markdown \
	--to=docx \
	--reference-doc=custom.docx \
	--dpi=300 \
	--output=./Luu.docx

Pandoc responded with:

Error running filter /Users/ian/.pandoc/removeHR:
Could not find executable /Users/ian/.pandoc/removeHR
```

You can see pandocomatic has rewritten to path relative to the root data-dir `/Users/ian/.pandoc/removeHR` which fails. Why not just let Pandoc handle the path resolution? If I specify an absolute path then this works fine (which is what I've always done, but it would be nice to not need to specify absolute paths)...

(error resolution working nicely BTW!)
