### ISSUE TITLE
Very minor: header for pandocomatic manual 

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#42]
Hi, the header image on your manual page overflows the header line:

![screen shot 2017-09-19 at 23 28 14](https://user-images.githubusercontent.com/153905/30600581-7842c3bc-9d25-11e7-86b4-39ab76a14751.png)

The header doesn't seem to have a specified height, but ends up as 67px on my screen, and the image is specified as 83px (for screen width over 400px, <400px and it is 36px for header vs. 45px for image):

```css
@media only screen and (min-width: 401px) {
    body > header img.heerdebeer {
        height: 83px;
        margin-left: -6px;
    }
}
 
body > header {
    border-bottom: 1px solid black;
    padding-left: 1ex;
    padding-right: 2ex;
    position: relative;
    color: #1C1585;
    font-size: 0.9em;
}
```

This is very easily fixed by specifying the same height for header and image...
