### ISSUE TITLE
Converting to beamer produces .tex output not .pdf

### ISSUE THREAD

**Issue by bsag** [htdebeer/pandocomatic#51]
I'm working on a templates to produce Beamer PDF slides and handouts. However, it seems that pandocomatic adds a `.beamer` suffix to the output file, regardless of whether I specify a `.pdf` output filetype in the template, in the file frontmatter, or at the command line.

The file it produces is in `.tex` format, so I could post-process it to PDF, but it would be good to be able to do it all in one go.

Here's the output of the pandocomatic command using the -b switch:

```
pandoc	--from=markdown \
	--to=beamer \
	--standalone \
	--pdf-engine=xelatex \
	--toc \
	--dpi=300 \
	--include-in-header=/Users/bsag/Dropbox/Lib/texmf/tex/latex/metropolis_header.tex \
	--output=/Users/bsag/Dropbox/to\ install/demo/beamer-demo.beamer
Pandocomatic needed 0.2 seconds to convert 'beamer-demo.md'.
```

which is using this template:

```
metro-pres:
    pandoc:
      from: markdown
      to: beamer
      output: 'presentation.pdf'
      standalone: true
      pdf-engine: xelatex
      toc: true
      dpi: 300
      include-in-header: '/Users/bsag/Dropbox/Lib/texmf/tex/latex/metropolis_header.tex'
    metadata:
      theme: metropolis
```

Looking at the lib/pandocomatic/configuration.rb file, it looks like there's no entry in `FORMAT_TO_EXT` for beamer, so it gets the `to:` format as a file extension. Unlike writing a Markdown file to PDF via LaTeX, you have to specify the `to:` format as beamer to process it properly, but that means you need to set PDF output via the file extension. However, I guess if you add a mapping from beamer to PDF in `FORMAT_TO_EXT`, people would lose the ability to output to .tex, which is often useful if you need to tweak further. I haven't dug around further to see if you do something like this already, but perhaps if there's no mapping set up, pandocomatic could use the extension of the filename specified for output if there is one, and if not, fall back to the `to:` format or HTML.

Let me know if I've misunderstood and am doing something wrong! I love pandocomatic - it has really streamlined my use of pandoc, so thanks for creating it.
