### ISSUE TITLE
Position of --lua-filter?

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#54]
Hi Huub, Scrivener 2.1 has made a small change to enable Lua filters to work in any order: https://github.com/jgm/pandoc/issues/4196 — I don't quite know what pandocomatic's current behaviour is, I open this issue just as a placeholder for a bit of investigation when I get some more time…

**Comment by htdebeer** [comment]
I haven't made any special effort for lua-filters in pandocomatic. This suggests that the same issues as with pandoc will arise.

**Comment by iandol** [comment]
I had a quick test, using this template:

```yaml
  test-luafilters:
    pandoc:
      from: markdown
      to: markdown
      output: out.md
      standalone: true
      lua-filter:
        - 'filters/addToday.lua'
      filter: 
        - 'filters/addToday'
```

It seems in this case the lua-filter is called first as expected:

```
👉  pandocomatic -b test.md
pandoc	--from=markdown \
	--to=markdown \
	--standalone \
	--lua-filter=/Users/ian/.pandoc/filters/addToday.lua \
	--filter=/Users/ian/.pandoc/filters/addToday
Pandocomatic needed 0.4 seconds to convert 'test.md'.
```

Swap the order in the template and the order in the command-line also swaps so this is working for single filters. I also tested an array of filters and this is also working.

```yaml
  test-luafilters:
    pandoc:
      from: markdown
      to: markdown
      output: out.md
      standalone: true
      lua-filter:
        - 'filters/addToday.lua'
      filter: 
        - 'filters/addToday'
        - 'filters/removeHR'
```

```
👉  pandocomatic -b test.md
pandoc	--from=markdown \
	--to=markdown \
	--standalone \
	--lua-filter=/Users/ian/.pandoc/filters/addToday.lua \
	--filter=/Users/ian/.pandoc/filters/addToday \
	--filter=/Users/ian/.pandoc/filters/removeHR
Pandocomatic needed 0.4 seconds to convert 'test.md'.
```

Swap order and command-line order also swaps. So we can close this.
