### ISSUE TITLE
Custom options in YAML-File for own template

### ISSUE THREAD

**Issue by herculosh** [htdebeer/pandocomatic#55]
I started Pandocomatic a few days ago with `pandocomatic` and I am very pleased with it. :-) Great work, Huub. 

Now I have tried to use my personal template base to create my presentations. I thought I could create the whole configuration in YAML and work with template inheritance. It was not possible because of missing proerties, if i would add this to a seperated `.md` file i where working. 
Unfortunately, properties such as `subtitle`, `topic` and `header-includes` were not included in the templates.

When I look at the debug output I get a message from `paru` that the option cannot be recognized and is therefore skipped.

``` 
(35)   - convert init-pipeline.md -> init-pipeline.tex
The pandoc option 'pandoc_minted' (with value '{"language"=>"powershell", "attributes"=>"breaklines=true"}') is not recognized by paru. This option is skipped.
The pandoc option 'section_titles' (with value 'false') is not recognized by paru. This option is skipped.
The pandoc option 'links_as_notes' (with value 'true') is not recognized by paru. This option is skipped.
pandoc	--metadata=\{\"subtitle\"\=\>\"The\ PowerShell\ pipeline\"\} \
	--from=markdown \
	--to=beamer \
	--verbose \
	--slide-level=2 \
	--toc \
	--filter=/Users/myuser/Documents/gitrepos/doz-as/pandoc-minted-beamer.py

```

There are more options that are not recognized. e. g. `section_title` or `link_as_notes` which should be part of Pandoc. 

Is it possible to register own options or do I do something wrong in the configuration?

My configuration: 
```
settings:
  recursive: false
  follow-links: false
  skip: ['*.vim','*.py', 'test.md','*.yaml']
templates:
  author:
    metadata:
      author: herculosh
  presentation-meta:
    title: Powershell course
    metadata:
      institute: myinstitu
      date: Dezember 2018
      themaname: thema
  presentation-frontpage-t5:
    extends: ['presentation-meta','author']
    glob: ['as-modul-base.*']
    pandoc:
      template: templates/as-thema-beamer.tex
      standalone: true
      output: ../as-thema-5.tex
    metadata:
      header-includes:
        \usepackage{longtable}
        \usepackage{smartdiagram}
        \usesmartdiagramlibrary{additions}
  presentation:
    glob: ['init-pipeline.md','init-ausgabe.md','init-selectobject.md','init-whereobject.md']
    pandoc:
      from: markdown
      to: beamer
      verbose: true
      slide-level: 2
      standalone: false
      toc: true
      pandoc-minted:
        language: powershell
        attributes: breaklines=true
      filter: pandoc-minted-beamer.py
      section-titles: false
      links-as-notes: true
```
