### ISSUE TITLE
Additional Filters

### ISSUE THREAD

**Issue by atanasj** [htdebeer/pandocomatic#56]
Firstly, thanks for an awesome package. Very, very useful.  

Now, can you please tell me where additional filters get written on the `pandocomatic.yaml` file e.g., `lua-filters`, `pandoc-crossref`, `pandoc-fignos`, etc? I am using the very helpful workflow [Scrivomoatic](https://github.com/iandol/scrivomatic), put together by @iandol. However, whilst `pandoc-citeproc` works okay, the other filters I try and use do not.

Not sure what I am doing wrong. Any help would be *greatly* appreciated.  

Thanks in advance.

**Comment by htdebeer** [comment]
An example of what you're trying to do and goes wrong would be helpful to give some specific advice.

In general, however, you can define a `pandoc` section in a pandocomatic template. In the `pandoc` setting you can use all pandoc options you like including `filter`. The value of the `filters` property is a list of [paths](https://heerdebeer.org/Software/markdown/pandocomatic/#specifying-paths) to filters to run.

For example you have the following project structure for your document and filters:

```
my-document/
-  the-actual-document.md
-  filters/
   - number-chapters.rb
   - add-today.sh
```

you can specify an internal [pandocomatic template](https://heerdebeer.org/Software/markdown/pandocomatic/#pandocomatic-templates) that converts the actual document to HTML and runs your filters as follows (this is the content of `the-actual-document.md`:

```
---
title: My document
_pandocomatic:
  pandoc:
    from: markdown
    to: html
    filter:
    - ./filters/number-chapters.rb
    - ./filters/add-today.sh
...

# Introduction

All about my document ...
```

When you are in directory `my-document` you should be able to convert your document with pandocomatic via `pandocomatic -i the-actual-document.md -o my-doc.html`.

You can use [absolute paths to scripts and paths relative to pandocomatic's data directory as well](https://heerdebeer.org/Software/markdown/pandocomatic/#specifying-paths) to specify the filters you want to run.
