### ISSUE TITLE
Allow preprocessors to be found within directories from PATH

### ISSUE THREAD

**Issue by ngirard** [htdebeer/pandocomatic#60]
in `ConvertFileCommand.process()`, an error is raised when `command` cannot be found within `File.dirname(@src)`.

It would be nice to have `command` be searched within directories from PATH, allowing to use e.g. the [pp preprocessor](https://github.com/CDSoft/pp) as follows:

```
pandocomatic_:
    preprocessors: ['pp -html -import macros/my-macros.pp']
    pandoc:
        to: html5
        output: f.html
        standalone: true
```

A direct support for pp would be even better.
