### ISSUE TITLE
Use of --biblatex?

### ISSUE THREAD

**Issue by NianiaM** [htdebeer/pandocomatic#68]
I want to produce a `.tex` file along side both a `.docx` and `.pdf` file, however, I am not quite sure how to run the [--biblatex](https://pandoc.org/MANUAL.html#citation-rendering) command in the pandocomatic YAML file since it has no options. I tried putting an empty 'biblatex' key to follow the pandoc call, however, this did not work.

Apologies if I'm just being dense!

**Comment by htdebeer** [comment]
If I understand you correctly, you have a single markdown file and you want to convert it to PDF, DOCX, and LATEX. For the latter output format, you want to use pandoc's `--biblatex` option. I would do this as follows:

Given a bibtex file named `bibliography.bib` with the following content:

```bibtex
@online{ Beer2019a,
    author = {Huub de Beer},
    title = {Pandocomatic. Automate the use of pandoc},
    year = {2019},
    url = {https://heerdebeer.org/Software/markdown/pandocomatic/},
    urldate = {2019-04-11}
}
```

You can define three separate templates, one for each output format, in a pandocomatic configuration file called `config.yaml` like so:

```yaml
templates:
    base:
        pandoc:
            from: markdown
            bibliography: ./bibliography.bib
    pdf:
        extends: base
        pandoc:
            to: pdf
    docx:
        extends: base
        pandoc:
            to: docx
    latex:
        extends: base
        pandoc:
            to: latex
            biblatex: true
            standalone: true
```

In this configuration file, I have defined a "base" template to collect all settings that are shared by the three output formats. Then, for each output format, I extend the "base" template. Note how the "pdf" and "docx" templates are similar, but how the "latex" template differs. For the latter template I have to specify both "biblatex" as well as "standalone" to create a LaTeX output file that works (out of the box) with biblatex.

Now, for the actual document to convert, I created the markdown file `about_pandocomatic.md`:

```pandoc
---
title: All about pandocomatic
author: Huub de Beer
pandocomatic_:
    use-template:
    -   pdf
    -   docx
    -   latex
...

Read all about pandocomatic in [@Beer2019a].
```

This document has a title and an author, and it references the one item from the bibliography. In the internal pandocomatic template I have specified to use all three output templates. If I run this file through pandocomatic like so:

```bash
pandocomatic -c config.yaml -i about_pandocomatic.md
```

Three files are being generated: a DOCX file, a PDF file, and a LaTeX file.

Was this what you had in mind?
