### ISSUE TITLE
Only some options in pandocomatic.yaml work

### ISSUE THREAD

**Issue by lyndondrake** [htdebeer/pandocomatic#69]
With the following pandocomatic.yaml file, the LaTeX-specific options don't seem to get passed through to pandoc - or at least, they don't appear to have any effect on the tex file produced. If I copy and past the same YAML options into the top of the `.md` file, they take effect:

```
templates:
  general:
    pandoc:
      to: latex
      bibliography: /Users/lyndon/Documents/Writing/Workflow/bibliography.bib
      papersize: a4
      mainfont: Skolar PE
      mainfontoptions: Ligatures=TeX, Numbers=OldStyle
      fontsize: 10pt
      lang: en-GB
      otherlangs: [grc, he, syr]
      pdf-engine: lualatex

  academic-article:
    extends: ['general']
    pandoc:
      standalone: true
      csl: /Users/lyndon/Documents/Writing/Workflow/csl-styles/society-of-biblical-literature-fullnote-bibliography.csl
      documentclass: article
      numbersections: true
```

**Comment by htdebeer** [comment]
This is the correct behavior. In the `pandoc` property only [pandoc command-line options](https://pandoc.org/MANUAL.html#options) such as `to` and `bibliography` take effect. To set template variables, you either have to use a) the `metadata` property or b) the `metadata` command-line option. 

## Option a: use the `metadata` property

```yaml
templates:
  general:
    pandoc:
      to: latex
      bibliography: /Users/lyndon/Documents/Writing/Workflow/bibliography.bib
      pdf-engine: lualatex
    metadata:
      papersize: a4
      mainfont: Skolar PE
      mainfontoptions: Ligatures=TeX, Numbers=OldStyle
      fontsize: 10pt
      lang: en-GB
      otherlangs: [grc, he, syr]
```
## Option b: use `metadata` command line option in the `pandoc` property

```yaml
templates:
  general:
    pandoc:
      to: latex
      bibliography: /Users/lyndon/Documents/Writing/Workflow/bibliography.bib
      metadata: 
      - "papersize: a4"
      - "mainfont: Skolar PE"
      - "mainfontoptions: Ligatures=TeX, Numbers=OldStyle"
      - "fontsize: 10pt"
      - "lang: en-GB"
      - "otherlangs: [grc, he, syr]"
      pdf-engine: lualatex
```

Personally I prefer option a because it more clearly separates the pandoc command-line options from the document's metadata.

Does this solve your issue?
