### ISSUE TITLE
Error using pandoc reference-docx option

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#7]
Hi, I'm using Pandoc 1.19.2.1 and Pandocomatic 0.1.2 on macOS 10.12.4 and ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

I'm using the following YAML and I get a `undefined method 'reference-docx' for #<Paru::Pandoc:0x007fea7b05ba78> (NoMethodError)`

```yaml
---
templates:
  paper-with-references:
    preprocessors: []
    pandoc:
      from: markdown
      to: docx
      standalone: true
      filter: 
        - pandoc-citeproc
      bibliography: /Users/ian/.pandoc/core.bib
      csl: /Users/ian/.pandoc/apa.csl
      reference-docx: /Users/ian/.pandoc/custom-reference.docx
      dpi: 300
      toc: false
      mathjax: true
      base-header-level: 1
    postprocessors: []
  paper-no-references:
    preprocessors: []
    pandoc:
      from: markdown
      to: docx
      standalone: true
      reference-docx: /Users/ian/.pandoc/custom-reference.docx
      toc: false
      mathjax: true
    postprocessors: []
---
```

Here's the ruby error

```
👉  pandocomatic -c $HOME/.dotfiles/pandoc/pandocomatic.yaml -i min.md
/Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.2/lib/pandocomatic/command/convert_file_command.rb:136:in `block in pandoc': undefined method `reference-docx' for #<Paru::Pandoc:0x007fea7b05ba78> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.2/lib/pandocomatic/command/convert_file_command.rb:127:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.2/lib/pandocomatic/command/convert_file_command.rb:127:in `pandoc'
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.2/lib/pandocomatic/command/convert_file_command.rb:89:in `convert_file'
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.2/lib/pandocomatic/command/convert_file_command.rb:49:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.2/lib/pandocomatic/command/command.rb:81:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.2/lib/pandocomatic/pandocomatic.rb:101:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.2/bin/pandocomatic:3:in `<top (required)>'
	from /usr/local/bin/pandocomatic:23:in `load'
	from /usr/local/bin/pandocomatic:23:in `<main>'
```

Also while I'm here there is an error on your pandoc option documentation examples, you always say `cls` when it should be `csl`
