### ISSUE TITLE
Command line prints out incorrect output file name

### ISSUE THREAD

**Issue by lyndondrake** [htdebeer/pandocomatic#70]
If I run pandocomatic, it gives the input file name as the output file name it has written to. Despite this, it actually writes to a different output file name, correctly. It's just a confusing message:

```
~/D/W/W/T/pandocomatic $ pandocomatic pandocomatic-test.md
Pandocomatic needed 1.1 seconds to convert '/Users/lyndon/Documents/Writing/Workflow/Test/pandocomatic/pandocomatic-test.md' to 'pandocomatic-test.md'.
```

Despite the output, it has actually written to pandocomatic-test.tex (which is what I waned and expected.

**Comment by htdebeer** [comment]
This does look like a bug. Can you add a minimal version of `pandocomatic-test.md` so I can reproduce the issue on my end?

**Comment by lyndondrake** [comment]
```
---
  author: Lyndon Drake
  title: "Test document"
  institute: University of Oxford
  date: 28 November 2018
  abstract: A little test abstract

  pandocomatic_:
    use-template: academic-article
---


This is a test document.
```
