### ISSUE TITLE
Multioptions in Yaml not passed correctly to Pandoc

### ISSUE THREAD

**Issue by herculosh** [htdebeer/pandocomatic#72]
Hello Together

I am trying to integrate my own Minted Filter from Pandocomatic to Latex. 
In the pandocomatic configuration. It looks like this (please take a look to `pdf-engine-opt`):

```
  education-slides:
    glob: ['*.md']
    extends: ['author','date','beamertex']
    preprocessors: []
    pandoc:
      filter: 
        - filters/pandoc-minted-beamer.py #pandoc-citeproc # process citations
      from: markdown
      to: beamer
      pdf-engine: lualatex
      pdf-engine-opt: --shell-escape
      pdf-engine-opt: --aux-directory=temp
      standalone: true
```
 
if I now kick pandocomatic at this template, I get the following `--debug` output. 

```
pandoc	--filter=/Users/user/Documents/gitrepos/doz-ps-online/data-dir/filters/pandoc-minted-beamer.py \
	--from=markdown \
	--to=beamer \
	--pdf-engine=lualatex \
	--pdf-engine-opt=--aux-directory\=temp \
	--standalone \
	--output=/Users/user/Documents/gitrepos/doz-ps-online/output/Thema1.pdf
```

Pandoc responds with the following output on the console.

```
lualatex: unrecognized option '--aux-directory=temp'
lualatex: unrecognized option '--aux-directory=temp'
Error producing PDF.
! Package minted Error: You must invoke LaTeX with the -shell-escape flag.
```
It looks like both pdf options are not transferred to Pandoc. Is this a bug or have I made a mistake?

Thanks in Advance. Best Regards Ivo
