### ISSUE TITLE
Allow path search fallback for executable pandoc filters 

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#9]
Hi, if I use pandoc-citeproc as I would in Pandoc:

```yaml
    pandoc:
      filter: 
        - pandoc-citeproc
      bibliography: /Users/ian/.pandoc/core.bib
      csl: /Users/ian/.pandoc/apa.csl
```

I get an error telling me pandoc-citeproc couldn't be found. Running pandoc from the command line and pandoc-citeproc is available (it is on my path at /usr/local/bin/pandoc-citeproc, and if I use that path everything is OK). I'd like for pandocomatic to fallback and use the same path discovery as pandoc does.

```
👉  pandocomatic -c $HOME/.pandoc/pandocomatic.yaml -i min.md -o out.docx
pandoc: Error running filter /Users/ian/Desktop/SF_mmd/pandoc-citeproc:
Could not find executable '/Users/ian/Desktop/SF_mmd/pandoc-citeproc'.
Pandocomatic needed 0.1 seconds to convert 'min.md' to 'out.docx'.
```

Pandoc documentation description of filter path search:

> In order of preference, pandoc will look for filters in (1) a specified full or relative path (executable or non-executable), (2) $DATADIR/filters (executable or non-executable), & (3) $PATH (executable only)
