### ISSUE TITLE
passing input file to pandoc when pdf output is specified

### ISSUE THREAD

**Issue by ZBiener** [htdebeer/pandocomatic#90]
On latest OSX Catalina version, using latest pandoc, pandocomatic, and paru, I get the following issue.

When I compile my file from .md to .tex, using the default latex-refs setting, I get the .tex file I am expecting. It compiles properly. However, when I compile using a setting that outputs from md to tex to pdf, the execution hangs. 

This happens with every predefined format I have that outputs to PDF though tex. Here is an example of a the relevant part of pandocomatic.yaml:

```
#----------------------------------------------------------
 refs:
    extends: [user-info]
    pandoc:
      standalone: true
      verbose: true # verbose by default
      citeproc: true
      bibliography: "/Users/xxx/Library/texmf/bibtex/bib/BibDeskLibrary.json" 
      csl: csl/chicago-author-date.csl
      citation-abbreviations: cite-abbr.json # my journal abbreviations
      reference-links: true
    metadata:
      reference-section-title: References
      notes-after-punctuation: false
      link-citations: true 
      csl-hanging-indent: true
#-----------------------------------------------------------------------------
  syllabus-tex:
    extends: ['refs']
    pandoc:
      from: markdown+multiline_tables
      to: latex
      standalone: true
      template: templates/custom/syllabus.latex   

#-----------------------------------------------------------------------------
  syllabus-pdf:
    extends: ['syllabus-tex']
    pandoc:
      to: pdf
      pdf-engine: xelatex
```
If the input file specifies syllabus-tex, it is compiled to latex. If the input file specific syllabus-pdf, the command hangs.

The debug output of pandocomatic using with syllabus-pdf specified in the file is:
```
pandoc	--to=latex \
	--pdf-engine=xelatex \
	--standalone \
	--verbose \
	--citeproc \
	--csl=/Users/xxx/.pandoc/csl/chicago-author-date.csl \
	--citation-abbreviations=/Users/xxx/.pandoc/cite-abbr.json \
	--reference-links \
	--from=markdown+raw_tex \
	--filter=/Users/zvb1/.pandoc/filters/assimilateMetadata.rb \
	--template=/Users/zvb1/.pandoc/templates/custom.latex \
	--output=/Volumes/Data/paodf\ -\ xdf\ of\ sdf/wef/sdf\ 21.1\ 23r/test.pdf
```

Curiously, if I paste this back into the command line, and _supply the file to be processed as the last argument_, the file is processed properly.

Is it possible that the input file is somehow not being passed to pandoc? Does this indicate some issue in my install or ruby/paru/etc? When I command-c from the hanged processes, I get the following output:

```Traceback (most recent call last):
	18: from /Users/xxx/.rbenv/versions/2.7.1/bin/pandocomatic:23:in `<main>'
	17: from /Users/xxx/.rbenv/versions/2.7.1/bin/pandocomatic:23:in `load'
	16: from /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/pandocomatic-0.2.7.4/bin/pandocomatic:3:in `<top (required)>'
	15: from /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/pandocomatic-0.2.7.4/lib/pandocomatic/pandocomatic.rb:105:in `run'
	14: from /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/pandocomatic-0.2.7.4/lib/pandocomatic/command/convert_file_multiple_command.rb:98:in `execute'
	13: from /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/pandocomatic-0.2.7.4/lib/pandocomatic/command/convert_file_multiple_command.rb:98:in `each'
	12: from /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/pandocomatic-0.2.7.4/lib/pandocomatic/command/convert_file_multiple_command.rb:99:in `block in execute'
	11: from /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/pandocomatic-0.2.7.4/lib/pandocomatic/command/command.rb:129:in `execute'
	10: from /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/pandocomatic-0.2.7.4/lib/pandocomatic/command/convert_file_command.rb:86:in `run'
	 9: from /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/pandocomatic-0.2.7.4/lib/pandocomatic/command/convert_file_command.rb:135:in `convert_file'
	 8: from /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/pandocomatic-0.2.7.4/lib/pandocomatic/command/convert_file_command.rb:184:in `pandoc'
	 7: from /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/pandocomatic-0.2.7.4/lib/pandocomatic/command/convert_file_command.rb:184:in `chdir'
	 6: from /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/pandocomatic-0.2.7.4/lib/pandocomatic/command/convert_file_command.rb:218:in `block in pandoc'
	 5: from /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/paru-0.4.2.1/lib/paru/pandoc.rb:157:in `convert'
	 4: from /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/paru-0.4.2.1/lib/paru/pandoc.rb:318:in `run_converter'
	 3: from /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/2.7.0/open3.rb:101:in `popen3'
	 2: from /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/2.7.0/open3.rb:219:in `popen_run'
	 1: from /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/paru-0.4.2.1/lib/paru/pandoc.rb:321:in `block in run_converter'
/Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/paru-0.4.2.1/lib/paru/pandoc.rb:321:in `read': Interrupt
```

Thanks.
