### ISSUE TITLE
Allow for fallback template inheritance

### ISSUE THREAD

**Issue by plbt5** [htdebeer/pandocomatic#96]
### Current operation
On specifying a template, currently it is possible to extend an existing template (`extend: [<template_name>+]`). This works very well when both the inherited and the inheriting templates are specified in the same configuration file; when the (to be) inherited template has not been specified in this file, an error is thrown:

> /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/configuration.rb:748:in `block in extend_template`: undefined local variable or method `parent_template_name` for #<Pandocomatic::Configuration:0x00007fd7f89f15f0> (NameError)

### Feature request
Include a default fallback operation that allows to inherit templates (that are not specified in the same yaml-file as the inheriting template) from the `pandocomatic.yaml` file that is available in pandoc's default directory: `~/.local/share/pandoc/`. This allows for a more modular setup of pandocomatic configuration files, particular the availability of a baseline pandocomatic configuration that applies always (unless overwritten by a user-defined extending template, specified in a separate configuration file).

### Suggested Operation
Assume the following excerpt of a user-defined local `myInterestingPaperProject/pandocomatic.yaml`:
```
# File: ~/Documents/publications/myInterestingPaperProject/pandocomatic.yaml 
# My pandocomatic YAML specification for my interesting paper
templates:
  author:
    metadata:
      author: Huub de Beer
   ...
  myrefs:
    extends: ['author', 'refs']
    pandoc:
      bibliography: "./myInterestingPaper.bib" #bibtex file, in the current project folder
      csl: "./apa.csl" #CSL style file, in the current project folder 
      ...
      author: Hans de Wolf
```
Consider the following excerpt from the current `~/.local/share/pandoc/pandocomatic.yaml`:
```
...
#-----------------------------------------------------------------------------
  refs:
    pandoc:
      verbose: true # verbose by default
      citeproc: true
      bibliography: Core.json #JSON faster than BIB, symlinked within Pandoc data dir
      csl: csl/cell-doi.csl
      citation-abbreviations: cite-abbr.json # my journal abbreviations
      reference-links: true
    metadata:
      reference-section-title: Bibliography
      notes-after-punctuation: false
      link-citations: true 
      csl-hanging-indent: true
...
```
This configuration would have the following effect:
- `author: Hans de Wolf`       # Overwriting the locally defined author with the new author's name
- `bibliography: "./myInterestingPaper.bib"`    # Overwriting the generic json bib to this particular bib-file
- `csl: "./apa.csl"`     # Overwriting the generic `csl/cell-doi.csl` reference style to the apa-style as requested by the journal

### Caveat
On using identical template names for the (to be) inherited template between local and pandoc default specifications, i.e., one specified in the user-defined yaml-file and one with the exact same name specified in `~/.local/share/pandoc/pandocomatic.yaml`, the user-defined local specification of the template shall apply. This implies that it is not possible to merge two templates with identical names. 

I don't have a particular demand on excluding or allowing to merge values. I leave this to @htdebeer to decide how to bring this in accordance to the [extension rules](https://heerdebeer.org/Software/markdown/pandocomatic/#extending-pandocomatic-templates) as defined in the documentation.
