### ISSUE TITLE
Minor: handle empty pandoc declarations in templates

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#98]
While helping a user who faced the recent psych error, they mentioned they also got an error when commenting out the paru filter that triggered the psych error in their `pandocomatic.yaml`. They were commenting out the filter in a list but leaving the `filter:` specifier in place:

```yaml
  html:
    pandoc:
      from: markdown
      to: html5
      standalone: true
      number-sections: false
      section-divs: true
      mathjax: true
      filter: 
        #- filters/assimilateMetadata.rb #regularise metadata
      template: 'templates/custom.html'
```

This was causing a `nil` error:

```
:: Running: /Users/ian/.rbenv/shims/pandocomatic --debug mdata.md
::: An unexpected error has occurred. You can report this bug via https://github.com/htdebeer/pandocomatic/issues/new.
::: /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.7.8/lib/pandocomatic/configuration.rb:666:in `is_local_path?': undefined method `start_with?' for nil:NilClass (NoMethodError)
```

To be clear, the error is on the user end, but just wanted to mention this so you can choose if you want to guard against this.
